refresh_rate: 5 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: debug
  appenders:
    - stdout
loggers:
  rendezvous_server:
    level: debug
    appenders:
      - requests
    additive: false