refresh_rate: 5 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "%Y-%m-%dT%H:%M:%S"
root:
  level: debug
  appenders:
    - stdout
loggers:
  rendezvous_server:
    level: debug
    appenders:
      - requests
      - stdout
    additive: false