refresh_rate: 5 seconds
appenders:
  stdout:
    kind: console
  file:
    kind: file
    path: "log/std.log"
    encoder:
      pattern: "%Y-%m-%dT%H:%M:%S"
root:
  level: debug
  appenders:
    - stdout
loggers:
  rendezvous_client:
    level: debug
    appenders:
      - file
      - stdout
    additive: false