[package]
name = "file-sync-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.0"
async-std = "1"
serde = "1.0.151"
serde_json = "1.0"
log = "0.4"
